export const icons = [
    {
      value:'mdi-beach',
      icon:'mdi-beach'
    },
    {
      value:'mdi-silverware',
      icon:'mdi-silverware'
    },
    {
      value:'mdi-phone-classic',
      icon:'mdi-phone-classic'
    },
    {
      value:'mdi-gas-station',
      icon:'mdi-gas-station'
    },
    {
      value:'mdi-airplane',
      icon:'mdi-airplane'
    },
    {
      value:'mdi-gift',
      icon:'mdi-gift'
    },
    {
      value:'mdi-office',
      icon:'mdi-office'
    },
    {
      value:'mdi-television-classic',
      icon:'mdi-television-classic'
    },
    {
      value:'mdi-sofa',
      icon:'mdi-sofa'
    }
  ]